import { SSHConnection, ConnectionHistory } from './types';
import { v4 as uuidv4 } from 'uuid';

export function createDefaultConnection(overrides: Partial<SSHConnection> = {}): SSHConnection {
  return {
    id: uuidv4(),
    name: '',
    host: '',
    port: 22,
    username: 'root',
    authType: 'key',
    keyPath: '',
    password: '',
    color: '#10b981',
    tags: [],
    notes: '',
    groupId: '',
    createdAt: Date.now(),
    protocol: 'ssh',
    favorite: false,
    status: 'unknown',
    portForwards: [],
    timeout: 30,
    keepAliveInterval: 60,
    encoding: 'utf-8',
    startupCommands: [],
    envVars: {},
    fontSize: 14,
    theme: 'default',
    totalConnections: 0,
    avgSessionTime: 0,
    ...overrides,
  };
}

export function createHistoryEntry(conn: SSHConnection, status: ConnectionHistory['status'] = 'success', duration = 0, errorMessage?: string): ConnectionHistory {
  return {
    id: uuidv4(),
    connectionId: conn.id,
    connectionName: conn.name,
    host: conn.host,
    timestamp: Date.now(),
    duration,
    status,
    errorMessage,
  };
}

export function generateSSHCommand(conn: SSHConnection): string {
  let cmd = 'ssh';
  if (conn.port !== 22) cmd += ` -p ${conn.port}`;
  if (conn.authType === 'key' && conn.keyPath) cmd += ` -i "${conn.keyPath}"`;
  if (conn.authType === 'certificate' && conn.certPath) cmd += ` -o CertificateFile="${conn.certPath}"`;
  if (conn.jumpHost) {
    const jumpStr = conn.jumpUser ? `${conn.jumpUser}@${conn.jumpHost}` : conn.jumpHost;
    cmd += ` -J ${jumpStr}${conn.jumpPort && conn.jumpPort !== 22 ? `:${conn.jumpPort}` : ''}`;
  }
  conn.portForwards.filter(pf => pf.enabled).forEach(pf => {
    if (pf.type === 'local') cmd += ` -L ${pf.localPort}:${pf.remoteHost}:${pf.remotePort}`;
    if (pf.type === 'remote') cmd += ` -R ${pf.localPort}:${pf.remoteHost}:${pf.remotePort}`;
    if (pf.type === 'dynamic') cmd += ` -D ${pf.localPort}`;
  });
  if (conn.timeout !== 30) cmd += ` -o ConnectTimeout=${conn.timeout}`;
  if (conn.keepAliveInterval !== 60) cmd += ` -o ServerAliveInterval=${conn.keepAliveInterval}`;
  cmd += ` ${conn.username}@${conn.host}`;
  return cmd;
}

export function generatePuTTYCommand(conn: SSHConnection): string {
  let cmd = 'putty';
  if (conn.port !== 22) cmd += ` -P ${conn.port}`;
  if (conn.authType === 'key' && conn.keyPath) cmd += ` -i "${conn.keyPath.replace('.pem', '.ppk')}"`;
  cmd += ` ${conn.username}@${conn.host}`;
  return cmd;
}

export function generateRDPCommand(conn: SSHConnection): string {
  return `mstsc /v:${conn.host}:${conn.port} /u:${conn.username}`;
}

export function generateBatchScript(connections: SSHConnection[]): string {
  let script = '@echo off\r\n';
  script += 'REM Generated by SSH Manager Pro\r\n';
  script += `REM Date: ${new Date().toLocaleDateString()}\r\n\r\n`;
  connections.forEach(conn => {
    script += `echo Connecting to ${conn.name}...\r\n`;
    script += `start "${conn.name}" cmd /k "${generateSSHCommand(conn)}"\r\n\r\n`;
  });
  script += 'echo All connections launched!\r\n';
  script += 'pause\r\n';
  return script;
}

export function generatePowerShellScript(connections: SSHConnection[]): string {
  let script = '# Generated by SSH Manager Pro\r\n';
  script += `# Date: ${new Date().toLocaleDateString()}\r\n\r\n`;
  connections.forEach(conn => {
    script += `Write-Host "Connecting to ${conn.name}..." -ForegroundColor Cyan\r\n`;
    script += `Start-Process wt -ArgumentList 'new-tab --title "${conn.name}" ${generateSSHCommand(conn)}'\r\n\r\n`;
  });
  return script;
}

export function parseSSHConfig(config: string): Partial<SSHConnection>[] {
  const results: Partial<SSHConnection>[] = [];
  const lines = config.split('\n');
  let current: Partial<SSHConnection> | null = null;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;

    const match = trimmed.match(/^(\S+)\s+(.+)$/);
    if (!match) continue;

    const [, key, value] = match;

    if (key.toLowerCase() === 'host') {
      if (current && current.name) results.push(current);
      current = { name: value, host: value, protocol: 'ssh' };
    } else if (current) {
      switch (key.toLowerCase()) {
        case 'hostname': current.host = value; break;
        case 'port': current.port = parseInt(value); break;
        case 'user': current.username = value; break;
        case 'identityfile': current.keyPath = value.replace('~', 'C:\\Users\\%USERNAME%'); current.authType = 'key'; break;
      }
    }
  }
  if (current && current.name) results.push(current);
  return results;
}

export function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  const seconds = Math.floor(ms / 1000);
  if (seconds < 60) return `${seconds}s`;
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m ${seconds % 60}s`;
  const hours = Math.floor(minutes / 60);
  return `${hours}h ${minutes % 60}m`;
}

export function formatDate(timestamp: number): string {
  return new Date(timestamp).toLocaleString();
}
